import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { AppHeader, AppScreen, Card, palette, PrimaryButton, StatusPill } from "@/components/erp-ui";
import type { DiagnosticEvent } from "@/lib/erp-types";
import { useErpStore } from "@/lib/erp-store";

const meta = { success: { icon: "check-circle" as const, color: palette.success, label: "سليم" }, warning: { icon: "warning-amber" as const, color: palette.warning, label: "إجراء مطلوب" }, error: { icon: "error-outline" as const, color: palette.error, label: "خطأ" }, info: { icon: "info-outline" as const, color: palette.violet, label: "معلومة" } };
function DiagnosticCard({ item }: { item: DiagnosticEvent }) { const itemMeta = meta[item.type]; return <Card style={styles.card}><View style={styles.eventHead}><StatusPill label={itemMeta.label} tone={item.type === "success" ? "success" : item.type === "warning" ? "warning" : item.type === "error" ? "error" : "info"} /><View style={styles.eventCopy}><Text style={styles.eventTitle}>{item.title}</Text><Text style={styles.eventTime}>{item.timestamp}</Text></View><MaterialIcons name={itemMeta.icon} color={itemMeta.color} size={23} /></View><Text style={styles.eventDetail}>{item.detail}</Text></Card>; }

export default function DiagnosticsScreen() {
  const { diagnostics, settings, testConnection, addDiagnostic } = useErpStore();
  const explainNumberingCheck = () => { addDiagnostic({ title: "فحص ترقيم طلبات الصرف يحتاج مسؤول الخادم", detail: "لا يوفر API الحالي نقطة فحص قراءة فقط لترقيم PAYMENT_REQUEST. لا ينفذ التطبيق أي تعديل لقاعدة البيانات. شغّل Database/Scripts/20260820_diagnose_payment_request_numbering.sql على بيئة الخادم ثم أعد اختبار إنشاء طلب صرف.", type: "warning" }); };
  return <AppScreen><AppHeader title="مركز التشخيص" subtitle="الاتصال والعقود والترقيم" action={<Pressable onPress={() => router.push("/connection")} style={({ pressed }) => [styles.settings, pressed && styles.pressed]}><MaterialIcons name="tune" size={21} color="#FFFFFF" /></Pressable>} />
    <FlatList data={diagnostics} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} renderItem={({ item }) => <DiagnosticCard item={item} />} ListHeaderComponent={<><Card><View style={styles.healthHead}><StatusPill label={settings.state === "ready" ? "جاهز" : "غير متصل"} tone={settings.state === "ready" ? "success" : "error"} /><View style={styles.healthCopy}><Text style={styles.healthTitle}>حالة API</Text><Text style={styles.healthDetail}>http://{settings.host}:{settings.port}/api/health</Text></View><MaterialIcons name="health-and-safety" size={25} color={settings.state === "ready" ? palette.success : palette.error} /></View><View style={styles.controls}><PrimaryButton label="اختبار الاتصال" tone="outline" icon="sync" onPress={testConnection} style={styles.control} /><PrimaryButton label={settings.numberingReady ? "آخر حفظ أكد الترقيم" : "خطوات PAYMENT_REQUEST"} tone={settings.numberingReady ? "teal" : "navy"} icon="tag" onPress={explainNumberingCheck} style={styles.control} /></View></Card><View style={styles.callout}><MaterialIcons name="tips-and-updates" size={19} color={palette.warning} /><Text style={styles.calloutText}>حالة الترقيم لا تُحاكى في الجوال. إذا ظهر الخطأ «لا يوجد إعداد ترقيم نشط»، فالمسار الصحيح هو تشغيل الاستعلام التشخيصي الآمن ثم تهيئة الإعداد من قبل مسؤول قاعدة بيانات API، وليس تغيير رقم ثابت في الجوال.</Text></View><Text style={styles.eventsTitle}>أحداث الجلسة</Text></>} />
  </AppScreen>;
}

const styles = StyleSheet.create({ list: { padding: 18, paddingBottom: 33, gap: 10 }, settings: { width: 38, height: 38, borderRadius: 19, backgroundColor: "#FFFFFF22", alignItems: "center", justifyContent: "center" }, healthHead: { flexDirection: "row", alignItems: "center", gap: 10 }, healthCopy: { flex: 1, alignItems: "flex-end" }, healthTitle: { color: palette.text, fontWeight: "900", fontSize: 15, writingDirection: "rtl" }, healthDetail: { color: palette.muted, fontSize: 10, marginTop: 4, writingDirection: "ltr" }, controls: { marginTop: 15, flexDirection: "row", gap: 9 }, control: { flex: 1, minHeight: 44, paddingHorizontal: 8 }, callout: { padding: 13, borderRadius: 15, backgroundColor: "#FFF8E8", flexDirection: "row", gap: 9, alignItems: "flex-start", marginTop: 2 }, calloutText: { flex: 1, color: "#765100", fontSize: 12, textAlign: "right", writingDirection: "rtl", lineHeight: 18 }, eventsTitle: { marginTop: 13, color: palette.text, fontWeight: "900", fontSize: 17, textAlign: "right", writingDirection: "rtl" }, card: { marginBottom: 0 }, eventHead: { flexDirection: "row", alignItems: "center", gap: 9 }, eventCopy: { flex: 1, alignItems: "flex-end" }, eventTitle: { color: palette.text, fontSize: 14, fontWeight: "800", textAlign: "right", writingDirection: "rtl" }, eventTime: { color: palette.muted, fontSize: 10, marginTop: 3, writingDirection: "rtl" }, eventDetail: { marginTop: 12, color: palette.muted, fontSize: 12, textAlign: "right", writingDirection: "rtl", lineHeight: 18 }, pressed: { opacity: 0.75, transform: [{ scale: 0.97 }] } });
