using AlTayerERP.Desktop.Common;

namespace AlTayerERP.Desktop;

partial class FrmCities : BaseForm
{
    private System.ComponentModel.IContainer? components = null;
    protected override void Dispose(bool disposing) { if (disposing) components?.Dispose(); base.Dispose(disposing); }

    private void InitializeComponent()
    {
        mainTableLayout = new TableLayoutPanel(); panelButtons = new FlowLayoutPanel();
        btnNew = new Button(); btnSave = new Button(); btnEdit = new Button(); btnCancel = new Button(); btnReset = new Button(); btnRefresh = new Button(); btnSearch = new Button(); btnPrint = new Button(); btnClose = new Button();
        grpDataCard = new GroupBox(); tblDataCard = new TableLayoutPanel(); lblCityCode = new Label(); txtCityCode = new TextBox(); lblCityNameAr = new Label(); txtCityNameAr = new TextBox(); lblCityNameEn = new Label(); txtCityNameEn = new TextBox(); lblGovernorate = new Label(); cmbGovernorate = new ComboBox(); lblDisplayOrder = new Label(); numDisplayOrder = new NumericUpDown(); lblStatus = new Label(); chkIsActive = new CheckBox(); lblNotes = new Label(); txtNotes = new TextBox();
        grpSearchContainer = new GroupBox(); pnlSearchFilter = new FlowLayoutPanel(); lblSearch = new Label(); txtSearch = new TextBox(); lblFilterGovernorate = new Label(); cmbFilterGovernorate = new ComboBox(); lblFilterStatus = new Label(); cmbFilterStatus = new ComboBox(); btnApplyFilter = new Button();
        dgvCities = new DataGridView(); tblAuditSummary = new TableLayoutPanel(); grpCreationData = new GroupBox(); lblCreatedBy = new Label(); lblCreatedAt = new Label(); grpModificationData = new GroupBox(); lblModifiedBy = new Label(); lblModifiedAt = new Label(); grpCounters = new GroupBox(); lblEditCount = new Label(); lblPrintCount = new Label();
        mainTableLayout.SuspendLayout(); panelButtons.SuspendLayout(); grpDataCard.SuspendLayout(); tblDataCard.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)numDisplayOrder).BeginInit(); grpSearchContainer.SuspendLayout(); pnlSearchFilter.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)dgvCities).BeginInit(); tblAuditSummary.SuspendLayout(); grpCreationData.SuspendLayout(); grpModificationData.SuspendLayout(); grpCounters.SuspendLayout(); SuspendLayout();
        RightToLeft = System.Windows.Forms.RightToLeft.Yes; RightToLeftLayout = true; ClientSize = new Size(1080, 720); MinimumSize = new Size(900, 620); Text = "نظام الطائر السعيد - إدارة المدن"; BackColor = Color.FromArgb(248, 250, 252); Font = new Font("Segoe UI", 9F);
        mainTableLayout.Dock = DockStyle.Fill; mainTableLayout.ColumnCount = 1; mainTableLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F)); mainTableLayout.RowCount = 5; mainTableLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F)); mainTableLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 245F)); mainTableLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 85F)); mainTableLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F)); mainTableLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 75F));
        panelButtons.Dock = DockStyle.Fill; panelButtons.RightToLeft = System.Windows.Forms.RightToLeft.Yes; panelButtons.FlowDirection = FlowDirection.RightToLeft; panelButtons.Padding = new Padding(4); panelButtons.WrapContents = false;
        Button[] buttons = { btnNew, btnSave, btnEdit, btnCancel, btnReset, btnRefresh, btnSearch, btnPrint, btnClose }; string[] titles = { "+ جديد", "✔ حفظ", "✎ تعديل", "✖ إلغاء", "↺ إعادة", "↻ تحديث", "🔍 بحث", "🖨 طباعة", "🚪 إغلاق" }; Color[] colors = { Color.FromArgb(13, 148, 136), Color.FromArgb(37, 99, 235), Color.FromArgb(217, 119, 6), Color.FromArgb(100, 116, 139), Color.FromArgb(79, 70, 229), Color.FromArgb(2, 132, 199), Color.FromArgb(5, 150, 105), Color.FromArgb(124, 58, 237), Color.FromArgb(220, 38, 38) };
        for (var i = 0; i < buttons.Length; i++) { buttons[i].Text = titles[i]; buttons[i].Size = new Size(90, 35); buttons[i].Margin = new Padding(3); buttons[i].FlatStyle = FlatStyle.Flat; buttons[i].FlatAppearance.BorderSize = 0; buttons[i].BackColor = colors[i]; buttons[i].ForeColor = Color.White; buttons[i].Font = new Font("Segoe UI", 9F, FontStyle.Bold); buttons[i].Cursor = Cursors.Hand; panelButtons.Controls.Add(buttons[i]); }
        grpDataCard.Dock = DockStyle.Fill; grpDataCard.Text = "بيانات المدينة الأساسية"; grpDataCard.Font = new Font("Segoe UI", 9.5F, FontStyle.Bold); grpDataCard.Controls.Add(tblDataCard);
        tblDataCard.Dock = DockStyle.Fill; tblDataCard.Padding = new Padding(8); tblDataCard.ColumnCount = 5; tblDataCard.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 125F)); tblDataCard.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F)); tblDataCard.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 35F)); tblDataCard.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 125F)); tblDataCard.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F)); tblDataCard.RowCount = 5; for (var i = 0; i < 5; i++) tblDataCard.RowStyles.Add(new RowStyle(SizeType.Absolute, 42F));
        Label[] labels = { lblCityCode, lblCityNameAr, lblCityNameEn, lblGovernorate, lblDisplayOrder, lblStatus, lblNotes }; foreach (var label in labels) { label.Dock = DockStyle.Fill; label.TextAlign = ContentAlignment.MiddleRight; label.Font = new Font("Segoe UI", 9F, FontStyle.Bold); }
        Control[] inputs = { txtCityCode, txtCityNameAr, txtCityNameEn, cmbGovernorate, numDisplayOrder, chkIsActive, txtNotes }; foreach (var input in inputs) { input.Margin = new Padding(4, 4, 12, 4); input.Font = new Font("Segoe UI", 9F); }
        lblCityCode.Text = "كود المدينة *:"; lblCityNameAr.Text = "اسم المدينة (عربي) *:"; lblCityNameEn.Text = "اسم المدينة (إنجليزي):"; lblGovernorate.Text = "المحافظة التابعة *:"; lblDisplayOrder.Text = "ترتيب الظهور:"; lblStatus.Text = "حالة المدينة:"; lblNotes.Text = "ملاحظات:"; chkIsActive.Text = "مدينة نشطة"; chkIsActive.Checked = true; chkIsActive.AutoSize = true; txtNotes.Multiline = true;
        tblDataCard.Controls.Add(lblCityCode, 0, 0); tblDataCard.Controls.Add(txtCityCode, 1, 0); tblDataCard.Controls.Add(lblCityNameAr, 3, 0); tblDataCard.Controls.Add(txtCityNameAr, 4, 0); tblDataCard.Controls.Add(lblCityNameEn, 0, 1); tblDataCard.Controls.Add(txtCityNameEn, 1, 1); tblDataCard.Controls.Add(lblGovernorate, 3, 1); tblDataCard.Controls.Add(cmbGovernorate, 4, 1); tblDataCard.Controls.Add(lblDisplayOrder, 0, 2); tblDataCard.Controls.Add(numDisplayOrder, 1, 2); tblDataCard.Controls.Add(lblStatus, 3, 2); tblDataCard.Controls.Add(chkIsActive, 4, 2); tblDataCard.Controls.Add(lblNotes, 0, 3); tblDataCard.Controls.Add(txtNotes, 1, 3); tblDataCard.SetColumnSpan(txtNotes, 4); tblDataCard.SetRowSpan(txtNotes, 2); foreach (var input in new Control[] { txtCityCode, txtCityNameAr, txtCityNameEn, cmbGovernorate, numDisplayOrder, txtNotes }) input.Dock = DockStyle.Fill;
        grpSearchContainer.Dock = DockStyle.Fill; grpSearchContainer.Text = "البحث والتصفية السريعة"; grpSearchContainer.Font = new Font("Segoe UI", 9F, FontStyle.Bold); grpSearchContainer.Controls.Add(pnlSearchFilter); pnlSearchFilter.Dock = DockStyle.Fill; pnlSearchFilter.RightToLeft = System.Windows.Forms.RightToLeft.Yes; pnlSearchFilter.FlowDirection = FlowDirection.RightToLeft; pnlSearchFilter.Padding = new Padding(10, 10, 10, 6); lblSearch.Text = "بحث سريع:"; lblFilterGovernorate.Text = "المحافظة:"; lblFilterStatus.Text = "الحالة:"; foreach (var label in new[] { lblSearch, lblFilterGovernorate, lblFilterStatus }) { label.AutoSize = true; label.Margin = new Padding(6, 6, 4, 0); label.Font = new Font("Segoe UI", 9F, FontStyle.Bold); } txtSearch.Size = new Size(180, 28); cmbFilterGovernorate.Size = new Size(150, 28); cmbFilterStatus.Size = new Size(110, 28); btnApplyFilter.Text = "تطبيق التصفية"; btnApplyFilter.Size = new Size(110, 30); btnApplyFilter.BackColor = Color.FromArgb(37, 99, 235); btnApplyFilter.ForeColor = Color.White; btnApplyFilter.FlatStyle = FlatStyle.Flat; btnApplyFilter.FlatAppearance.BorderSize = 0; pnlSearchFilter.Controls.AddRange(new Control[] { lblSearch, txtSearch, lblFilterGovernorate, cmbFilterGovernorate, lblFilterStatus, cmbFilterStatus, btnApplyFilter });
        dgvCities.Dock = DockStyle.Fill; dgvCities.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill; dgvCities.BackgroundColor = Color.White; dgvCities.BorderStyle = BorderStyle.Fixed3D; dgvCities.ColumnHeadersHeight = 32; dgvCities.RowTemplate.Height = 26; dgvCities.SelectionMode = DataGridViewSelectionMode.FullRowSelect; dgvCities.MultiSelect = false; dgvCities.ReadOnly = true; dgvCities.AllowUserToAddRows = false; dgvCities.AlternatingRowsDefaultCellStyle.BackColor = Color.FromArgb(241, 245, 249); dgvCities.DefaultCellStyle.SelectionBackColor = Color.FromArgb(37, 99, 235);
        tblAuditSummary.Dock = DockStyle.Fill; tblAuditSummary.ColumnCount = 3; tblAuditSummary.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.33F)); tblAuditSummary.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.33F)); tblAuditSummary.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.33F)); ConfigureAuditGroup(grpCreationData, "بيانات الإنشاء", lblCreatedBy, "أنشئ بواسطة: -", lblCreatedAt, "تاريخ الإنشاء: -"); ConfigureAuditGroup(grpModificationData, "بيانات التعديل", lblModifiedBy, "عدل بواسطة: -", lblModifiedAt, "تاريخ التعديل: -"); ConfigureAuditGroup(grpCounters, "العدادات", lblEditCount, "عدد التعديلات: -", lblPrintCount, "عدد مرات الطباعة: -"); tblAuditSummary.Controls.Add(grpCreationData, 0, 0); tblAuditSummary.Controls.Add(grpModificationData, 1, 0); tblAuditSummary.Controls.Add(grpCounters, 2, 0);
        mainTableLayout.Controls.Add(panelButtons, 0, 0); mainTableLayout.Controls.Add(grpDataCard, 0, 1); mainTableLayout.Controls.Add(grpSearchContainer, 0, 2); mainTableLayout.Controls.Add(dgvCities, 0, 3); mainTableLayout.Controls.Add(tblAuditSummary, 0, 4); Controls.Add(mainTableLayout);
        mainTableLayout.ResumeLayout(false); panelButtons.ResumeLayout(false); grpDataCard.ResumeLayout(false); tblDataCard.ResumeLayout(false); ((System.ComponentModel.ISupportInitialize)numDisplayOrder).EndInit(); grpSearchContainer.ResumeLayout(false); pnlSearchFilter.ResumeLayout(false); ((System.ComponentModel.ISupportInitialize)dgvCities).EndInit(); tblAuditSummary.ResumeLayout(false); grpCreationData.ResumeLayout(false); grpModificationData.ResumeLayout(false); grpCounters.ResumeLayout(false); ResumeLayout(false);
    }

    private static void ConfigureAuditGroup(GroupBox group, string title, Label first, string firstText, Label second, string secondText) { group.Text = title; group.Dock = DockStyle.Fill; group.Font = new Font("Segoe UI", 8F); first.Text = firstText; first.Dock = DockStyle.Top; second.Text = secondText; second.Dock = DockStyle.Top; group.Controls.Add(second); group.Controls.Add(first); }
    private TableLayoutPanel mainTableLayout = null!; private FlowLayoutPanel panelButtons = null!; private Button btnNew = null!, btnSave = null!, btnEdit = null!, btnCancel = null!, btnReset = null!, btnRefresh = null!, btnSearch = null!, btnPrint = null!, btnClose = null!; private GroupBox grpDataCard = null!; private TableLayoutPanel tblDataCard = null!; private Label lblCityCode = null!, lblCityNameAr = null!, lblCityNameEn = null!, lblGovernorate = null!, lblDisplayOrder = null!, lblStatus = null!, lblNotes = null!; private TextBox txtCityCode = null!, txtCityNameAr = null!, txtCityNameEn = null!, txtNotes = null!; private ComboBox cmbGovernorate = null!; private NumericUpDown numDisplayOrder = null!; private CheckBox chkIsActive = null!; private GroupBox grpSearchContainer = null!; private FlowLayoutPanel pnlSearchFilter = null!; private Label lblSearch = null!, lblFilterGovernorate = null!, lblFilterStatus = null!; private TextBox txtSearch = null!; private ComboBox cmbFilterGovernorate = null!, cmbFilterStatus = null!; private Button btnApplyFilter = null!; private DataGridView dgvCities = null!; private TableLayoutPanel tblAuditSummary = null!; private GroupBox grpCreationData = null!, grpModificationData = null!, grpCounters = null!; private Label lblCreatedBy = null!, lblCreatedAt = null!, lblModifiedBy = null!, lblModifiedAt = null!, lblEditCount = null!, lblPrintCount = null!;
}
